version: 1.0.{build}
image: Visual Studio 2015

configuration:
  - dynamic
#  - static

environment:
  matrix:
  - TOOLCHAIN_VERSION: 9.0
  - TOOLCHAIN_VERSION: 10.0
  - TOOLCHAIN_VERSION: 11.0
  - TOOLCHAIN_VERSION: 12.0
  - TOOLCHAIN_VERSION: 14.0

platform:
- x86
- x64

build_script:
- cmd: ci/build.bat

test_script:
- cmd: ci/build.bat runtests
