# AppVeyor configuration for EPICS Base

# Ralph Lange <ralph.lange@gmx.de>
# Copyright (c) 2016 ITER Organization

# Version format
version: 1.0.{build}

# Called at very beginning, before repo cloning
init:
  # Set autocrlf to make batch files work
  - git config --global core.autocrlf true

# Set clone depth (do not fetch complete history)
clone_depth: 2

# Skipping commits affecting only specific files
skip_commits:
  files:
    - 'documentation/*'
    - 'templates/*'
    - '**/*.html'
    - '**/*.md'

# Build Configuration as axis for matrix build
configuration:
  - dynamic
  - static
  - dynamic-debug
  - static-debug

# Environment variables as axis for matrix build
environment:
  matrix:
  - TOOLCHAIN: 9.0
  - TOOLCHAIN: 10.0
  - TOOLCHAIN: 11.0
  - TOOLCHAIN: 12.0
  - TOOLCHAIN: 14.0
  - TOOLCHAIN: cygwin
  - TOOLCHAIN: mingw

# Platform as axis for matrix build
platform:
  - x86
  - x64

# Matrix configuration: allow specific failing jobs
matrix:
  allow_failures:
  # VS Express installs don't have the 64 bit compiler
  - platform: x64
    TOOLCHAIN: 9.0
  - platform: x64
    TOOLCHAIN: 10.0

install:
  - cmd: ci/appveyor_install.bat

build_script:
  - cmd: ci/appveyor_make.bat

test_script:
  - cmd: ci/appveyor_make.bat runtests

#---------------------------------#
#         notifications           #
#---------------------------------#

- provider: Slack
  incoming_webhook:
    secure: RYOm3FIUYeZGjWKaeTVKwq+C3fzK54AKwbmAoECED45mex3lN+8HmrC845a6mg9xPUJ/ND51RopWVaKDD9/UzaM0SO195RQLKqUTIUafiuM=
