version: 1.0.{build}
image:
- Visual Studio 2015
- Visual Studio 2013

environment:
  matrix:
  - STATIC: YES
  - STATIC: NO

platform:
- x86
- x64

build_script:
- cmd: ci/build.bat

test_script:
- cmd: ci/build.bat runtests
