version: 1.0.{build}
image:
- Visual Studio 2015
- Visual Studio 2013

environment:
  matrix:
  - STATIC: YES
  - STATIC: NO

platform:
- x86
- x64

build_script:
- cmd: |
    set "STATIC= "
    if "%STATIC%" == YES set STATIC=-static
    reg Query "HKLM\Hardware\Description\System\CentralProcessor\0" | find /i "x86" > NUL && set OS=32BIT || set OS=64BIT
    If %OS% == 64BIT (
        set EPICS_HOST_ARCH=windows-x64%STATIC%
        set COMPILER=amd64
    ) ELSE (
        set EPICS_HOST_ARCH=win32-x86%STATIC%
        set COMPILER=x86
    )
    for /l %%X in (14,-1,8) do (
        if exist "C:\Program Files (x86)\Microsoft Visual Studio %%X.0\VC\vcvarsall.bat" (
            "C:\Program Files (x86)\Microsoft Visual Studio %%X.0\VC\vcvarsall.bat" %COMPILER%
            goto :BUILD
        )
    )
    :BUILD
    C:\MinGW\bin\mingw32-make

test_script:
- cmd: |
    set "STATIC= "
    if "%STATIC%" == YES set STATIC=-static
    reg Query "HKLM\Hardware\Description\System\CentralProcessor\0" | find /i "x86" > NUL && set OS=32BIT || set OS=64BIT
    If %OS% == 64BIT (
        set EPICS_HOST_ARCH=windows-x64%STATIC%
        set COMPILER=amd64
    ) ELSE (
        set EPICS_HOST_ARCH=win32-x86%STATIC%
        set COMPILER=x86
    )
    for /l %%X in (14,-1,8) do (
        if exist "C:\Program Files (x86)\Microsoft Visual Studio %%X.0\VC\vcvarsall.bat" (
            "C:\Program Files (x86)\Microsoft Visual Studio %%X.0\VC\vcvarsall.bat" %COMPILER%
            goto :BUILD
        )
    )
    :BUILD
    C:\MinGW\bin\mingw32-make runtests
    