version: 1.0.{build}
image: Visual Studio 2015

configuration:
  - dynamic
  - static

environment:
  matrix:
    - TOOLCHAIN: 9.0
    - TOOLCHAIN: 10.0
    - TOOLCHAIN: 11.0
    - TOOLCHAIN: 12.0
    - TOOLCHAIN: 14.0

platform:
  - x86
  - x64

matrix:
  allow_failures:
# MSVC 11.0 is not installed for 64bit
    - platform: x64
      TOOLCHAIN: 11.0

build_script:
  - cmd: ci/build.bat

test_script:
  - cmd: ci/build.bat runtests
