version: 1.0.{build}

configuration:
  - dynamic
  - static
  - dynamic-debug
  - static-debug

environment:
  matrix:
  - TOOLCHAIN: 9.0
  - TOOLCHAIN: 10.0
  - TOOLCHAIN: 11.0
  - TOOLCHAIN: 12.0
  - TOOLCHAIN: 14.0
  - TOOLCHAIN: cygwin
  - TOOLCHAIN: mingw

platform:
  - x86
  - x64

matrix:
  allow_failures:
# MSVC 11.0 is not installed for 64bit on Express installs
  - platform: x64
    TOOLCHAIN: 9.0
  - platform: x64
    TOOLCHAIN: 10.0
  - platform: x64
    TOOLCHAIN: 11.0

install:
  - cmd: ci/appveyor_install.bat

build_script:
  - cmd: ci/appveyor_make.bat

test_script:
  - cmd: ci/appveyor_make.bat runtests
