# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    dir
    dir C:\Windows
    dir C:\
    dir C:\"Program Files (x86)"
    dir C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC
  displayName: 'Run a multi-line script'
  
- bash: |
    echo I am a bash script
    ls -al
    ls -al /
  displayName: 'Run a bash script'
